### PR TITLE
Fix community posting

### LINKED ISSUE #289: Posting in a community
**Describe the bug**

The post button in communities isn't working

**To Reproduce**

Go to a community and click post

### PR DESCRIPTION
**Pull request by carina-akaia**
Fixes #289

### CODE REVIEW

**Review by ailisp — APPROVED** [review]
Code looks good. Do you have a preview link for this fix?

**Comment by carina-akaia** [comment]
> Do you have a preview link for this fix?

No, but I'll deploy it later today

**Comment by carina-akaia** [comment]
@ailisp here's the preview link:

https://near.social/carina.akaia.near/widget/gigs-board.pages.community.activity?handle=devhub-test&nearDevGovGigsContractAccountId=devgovgigs.near

**Comment by ailisp** [comment]
@carina-akaia preview works well. Nice!

Currently CI is broken, let's not merge until that's fixed

**Pull request merged**
