### PR TITLE
Feat/275 featured communites revisited

### PR DESCRIPTION
**Pull request by Tguntenaar**
_Resolves #275_

[Preview](https://near.org/geforcy.near/widget/app?page=admin)

Acceptance Criteria:

- [x] An "Admin" link is visible in the header navigation, visible and accessible only to DevHub admins (not community admins!)
- [x] When a DevHub admin clicks the Admin button, they see a settings page with section for configuring the featured communities
- [x] Within the settings section, DevHub admins can edit communities to display on the homepage. The interface for this can be super simple ... just need to solve the goal.
- [x] The UI show a maximum of 5 featured communities, to support the current display limit
Once the admin clicks save, the changes are instantly reflected on the homepage
- [x] The admin UI should prevent the user from accidentally showing fewer than 4 communities.

### CODE REVIEW

**Review by ailisp — COMMENTED** [review]
The featured community part of implementation looks great and testing also looks good. The preview is also functioning, but part of #388 is mixed in this PR and there's some issue with #388. Could you keep only featured community part of changes in this PR?

**Comment by Tguntenaar** [comment]
@ailisp I closed #275 ticket to combine it with issue #315 them both in PR #388. Didn't realise I forgot to close this PR.

**Comment by Tguntenaar** [comment]
I will close this PR now in favor of #388

**Comment by ailisp** [comment]
@Tguntenaar Sorry I didn't see the latest discussion on issue. Don't worry about this:
 
> How should I manage communication moving forward? I can share updates on both the pull request and the issue; of course, it could become overly spammy that way.

Let's close issue and PRs as soon as it's not relevant, if sometimes it's not closed in time, it's also not a big problem, some outdated message will be like this one, just like peers in a distributed system :D

**Pull request closed without merging**
