### PR TITLE
fix: Load posts asynchronously

### LINKED ISSUE #166: Community Activity is too heavy with many posts on it
**Describe the bug**

Community Activity feed does not use InfiniteScroll and freezes the page for communities with many posts (e.g. ZK)

https://github.com/near/neardevhub-widgets/blob/cb7b40709016a63f9ad49ac33f2614fd8198fcf5/src/gigs-board/pages/community/activity.jsx#L130-L132 - this is a naive implementation instead of a proper one:

https://github.com/near/neardevhub-widgets/blob/e6866d2158013944fef0de5a15642a3313aac95a/src/gigs-board/components/posts/List.jsx#L427-L434

**To Reproduce**
1. Go to https://near.org/root.akaia.near/widget/gigs-board.pages.community.activity?handle=zero-knowledge&nearDevGovGigsContractAccountId=devgovgigs.near
2. You cannot interact with the page until it loads ALL the posts

**Expected behavior**

The page should be interactive quickly - InfiniteScroll helps with lazy loading.

### PR DESCRIPTION
**Pull request by near-akaia-root**
Closes #166 

## Preview

Mainnet: https://near.org/root.akaia.near/widget/gigs-board.pages.community.activity?handle=zero-knowledge&nearDevGovGigsContractAccountId=devgovgigs.near

### CODE REVIEW

**Review by ailisp — COMMENTED** [review]
This fix looks good, but it mixed with changes from another PR, please cherry pick the last commit, rebase it onto a new branch from main and create a new PR

**Comment by near-akaia-root** [comment]
> This fix looks good, but it mixed with changes from another PR, please cherry pick the last commit, rebase it onto a new branch from main and create a new PR

This branch is meant to be merged after #179, can I just sync it once #main is updated?

**Comment by ailisp** [comment]
Yes you can but I don't recommend to do this in the future - a more git idiomatic workflow when you work on several issues: both create branch from one. If one branch is merged first, pull main from upstream and merge it to the other one.

**Comment by near-akaia-root** [comment]
Yeah, apologies, I applied the wrong approach here

**Comment by near-akaia-root** [comment]
@ailisp fixed

**Comment by ailisp** [comment]
@near-akaia-root One small thing, at home page posts are by default compacted (with "Read More"):
image

But at community activity they're not:
image

And actually the posts are quite lengthy, so we want the compact behavior  at community activity too

**Comment by near-akaia-root** [comment]
@ailisp it is also fixed in this branch

**Comment by near-akaia-root** [comment]
UPD:

## Preview

Mainnet: https://near.org/root.akaia.near/widget/gigs-board.pages.community.activity?handle=zero-knowledge&nearDevGovGigsContractAccountId=devgovgigs.near

**Review by ailisp — APPROVED** [review]
Looks great!

**Pull request merged**
