### PR TITLE
add contributors file

### PR DESCRIPTION
**Pull request by DeleMike**
_Fixes: #506_

### CODE REVIEW

**Comment by DeleMike** [comment]
@ailisp, please review. what am I missing out?
I followed the All Contributors [Docs](https://allcontributors.org/docs/en/bot/usage) as a guide.

**Comment by ailisp** [comment]
@allcontributors please add @DeleMike for add contributors file.

**Comment by ailisp** [comment]
@allcontributors please add @DeleMike for infra

**Comment by ailisp** [comment]
Thank you @DeleMike !

**Comment by ailisp** [comment]
@all-contributors 
please add @nearmax for code.
please add @ailisp for code. 
please add @frol for code.
please add @carina-akaia for code.
please add @elliotBraem for code.
please add @itexpert120 for code.
please add @Tguntenaar for code.
please add @petersalomonsen for code.
please add @jaswinder6991 for code.
please add @ori-near for code.
please add @Megha-Dev-19 for code.
please add @espensimensen for code.
please add @DeleMike for code.
please add @frolvanya for code.
please add @ben-jamming-reilly for code.
please add @projectnoa for code.

**Comment by ailisp** [comment]
@all-contributors 
please add @nearmax for code.
please add @ailisp for code. 
please add @frol for code.
please add @carina-akaia for code.
please add @elliotBraem for code.
please add @itexpert120 for code.
please add @Tguntenaar for code.
please add @petersalomonsen for code.
please add @jaswinder6991 for code.
please add @ori-near for code.
please add @Megha-Dev-19 for code.
please add @espensimensen for code.
please add @DeleMike for code.
please add @frolvanya for code.
please add @ben-jamming-reilly for code.
please add @projectnoa for code.

**Comment by ailisp** [comment]
https://github.com/all-contributors
please add @nearmax for code.
please add @ailisp for code.
please add @frol for code.
please add @carina-akaia for code.
please add @elliotBraem for code.
please add @itexpert120 for code.
please add @Tguntenaar for code.
please add @petersalomonsen for code.
please add @jaswinder6991 for code.
please add @ori-near for code.

**Comment by ailisp** [comment]
@allcontributors
please add @nearmax for code.
please add @ailisp for code.
please add @frol for code.
please add @carina-akaia for code.
please add @elliotBraem for code.
please add @itexpert120 for code.
please add @Tguntenaar for code.
please add @petersalomonsen for code.
please add @jaswinder6991 for code.
please add @ori-near for code.

**Comment by ailisp** [comment]
@allcontributors
please add @nearmax for code.
please add @ailisp for code.
please add @frol for code.
please add @carina-akaia for code.
please add @elliotBraem for code.

**Comment by ailisp** [comment]
@all-contributors
please add @nearmax for code.
please add @ailisp for code.
please add @frol for code.
please add @carina-akaia for code.
please add @elliotBraem for code.
please add @itexpert120 for code.
please add @Tguntenaar for code.
please add @petersalomonsen for code.
please add @jaswinder6991 for code.
please add @ori-near for code.
please add @Megha-Dev-19 for code.
please add @espensimensen for code.
please add @DeleMike for code.
please add @frolvanya for code.
please add @ben-jamming-reilly for code.
please add @projectnoa for code.

**Comment by ailisp** [comment]
@DeleMike Thanks for your contribution! Seems allcontributors are quite unreliable, as you can see from this PR it at least have three problems:
1. It cannot simply read from git history automatically and require manual add contributors
2. It has problems on recognize the allcontributor configuration after merge your PR, and only work after I revert your PR
3. Even after that, trying to add multiple contributors it only recorgnize the first, doesn't match the behavior in its doc: https://allcontributors.org/docs/en/bot/usage#using-multiple-lines

Could you please try other alternative tool/service than allcontributors?

**Comment by DeleMike** [comment]
> @DeleMike Thanks for your contribution! Seems allcontributors are quite unreliable, as you can see from this PR it at least have three problems:
> 
> 1. It cannot simply read from git history automatically and require manual add contributors
> 2. It has problems on recognize the allcontributor configuration after merge your PR, and only work after I revert your PR
> 3. Even after that, trying to add multiple contributors it only recorgnize the first, doesn't match the behavior in its doc: https://allcontributors.org/docs/en/bot/usage#using-multiple-lines
> 
> Could you please try other alternative tool/service than allcontributors?

Thanks @ailisp for the updates! do I still go ahead to try another tool/service?

**Comment by ailisp** [comment]
@DeleMike Looks like it's just taking time for all-contributors bot to create PRs for all contributors, and it's one contributor per PR - will cause merge conflict if merge them one by one. I merged on of the PRs, could you please make a PR to all all contributors in one PR manually?

**Comment by DeleMike** [comment]
@ailisp, alright. I am looking into it.

**Pull request merged**
