### PR TITLE
Fix community sidebar issues

### LINKED ISSUE #235: [Communities] Homepage stuck in loading state and won't display sidebar
**Describe the bug**
I just created a new [Developer DAO community](https://near.social/devgovgigs.near/widget/gigs-board.pages.community.activity?handle=devdao). However, the homepage is stuck in a loading state and won't display the sidebar. I assume this is maybe because there are many posts on DevHub with the community tag `developer-dao`?

**To Reproduce**
1. Go to https://near.social/devgovgigs.near/widget/gigs-board.pages.community.activity?handle=devdao
2. See two errors: 
- Loading icon under the user profile of the first post
- Sidebar shows "Loading..." text 

**Expected behavior**
The page should load quickly and display all the author photos + the sidebar content/

**Screenshots**
Screenshot 2023-08-09 at 4 58 40 PM

**Desktop (please complete the following information):**
 - OS: Mac
 - Browsers: Chrome, Safari
 - Version: Latest versions

### PR DESCRIPTION
**Pull request by carina-akaia**
Closes #235 
In addition, makes links for any zero-length 3rd party service handles hidden

## Preview

[Mainnet](https://near.social/carina.akaia.near/widget/gigs-board.pages.community.activity?handle=near-discovery&nearDevGovGigsContractAccountId=devgovgigs.near)

### CODE REVIEW

**Review by ailisp — COMMENTED** [review]
It mostly looks good. One issue is team admins are not displayed, only global moderators, which I think it's a bug (it also shows in current production). @ori-near can you confirm whether this is expected?

For example, contract-standard community:

https://near.social/devgovgigs.near/widget/gigs-board.pages.community.activity?handle=contract-standards

It has these admins: https://near.social/devgovgigs.near/widget/gigs-board.pages.community.teams?handle=contract-standards

**Comment by carina-akaia** [comment]
@ailisp I'm looking into it

**Comment by ori-near** [comment]
> It mostly looks good. One issue is team admins are not displayed, only global moderators, which I think it's a bug (it also shows in current production). @ori-near can you confirm whether this is expected?

Hey @ailisp – you are right, this is a bug. We need to only show Community Admins. 

@carina-akaia Please let me now if I should create a new bug for this or if you want to fix this as part of this.

**Comment by carina-akaia** [comment]
@ori-near I'd prefer to merge this PR and create a separate ticket in order to delegate it to someone else, as I don't have the capacity to keep up with the sidebar

**Comment by carina-akaia** [comment]
@ori-near please check out this [**preview**](https://near.social/carina.akaia.near/widget/gigs-board.pages.community.activity?handle=near-discovery&nearDevGovGigsContractAccountId=devgovgigs.near) and let me know whether any additional changes are required or not

**Comment by ailisp** [comment]
Code looks updated but preview didn't update and still showing moderators, @carina-akaia can you update the preview?

**Comment by carina-akaia** [comment]
@ailisp apologies, I redeployed another branch to that account by accident. Fixed!

**Comment by ailisp** [comment]
@carina-akaia the preview is still not fixed:
https://near.social/root.akaia.near/widget/gigs-board.pages.community.activity?handle=contract-standards&nearDevGovGigsContractAccountId=devgovgigs.near

I suspect your deployment didn't succeed, because changes below doesn't reflect in the preview
image

**Comment by carina-akaia** [comment]
@ailisp check https://near.social/carina.akaia.near/widget/gigs-board.pages.community.activity?handle=near-discovery&nearDevGovGigsContractAccountId=devgovgigs.near

( also updated the link in the description )

**Comment by ori-near** [comment]
Hi @carina-akaia thanks for posting this. Right now the GitHub link is incorrect ... but it's because the user entered "https://github.com/near/near-discovery" instead of just handle. I'll fix this on the community settings page, but we will address this potential user error in: https://github.com/near/neardevhub-widgets/issues/173.

**Review by ailisp — APPROVED** [review]

**Pull request merged**
