### PR TITLE
Display featured communities using get_featured_communities

### PR DESCRIPTION
**Pull request by jaswinder6991**
This commit helps to fetch featured communities from the smart contract. 
Resolves https://github.com/near/neardevhub-widgets/issues/176

### CODE REVIEW

**Review by ailisp — APPROVED** [review]
Code looks good. @jaswinder6991 Do you have a preview deploy of this widget?

**Comment by jaswinder6991** [comment]
Hi @ailisp, sorry for the late reply but here it is:
https://test.near.org/devhubopen.testnet/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=dev-1690178072552-64500913410571&nearDevGovGigsWidgetsAccountId=devhubopen.testnet

**Comment by jaswinder6991** [comment]
Hey @ailisp, I ran prettier manually only for the gigs-board.Pages.Feed.jsx file as it was the only one I made changes to. When I ran npm run fmt, it formatted a whole lot of other files too. I think the main branch being created before the CI pipeline was implemented has "non-pretty" files in it. 

Should I run npm run fmt and push that commit? or I can submit a PR differently which fixes the pretty issue in main first and then we can merge this branch?

**Comment by ailisp** [comment]
@jaswinder6991 I just checked main branch has formatted and accepted by CI. So I guess the problem can be your local prettier config override the default config used in CI. Given there is a number of open PRs that rely on the main branch default prettier config, and we don't want formatting related conflicts in all these PRs. Could you try figure out what the default prettier config is and have it explicitly commit to the repo? For this PR, you local prettier should also pick up this explicitly commited config.

**Comment by jaswinder6991** [comment]
Hi @ailisp, turns out my local prettier config had "trailing commas": "ES5", seems like it is "none" in the CI config. Pushed a new commit.

**Pull request merged**
