### PR TITLE
Support buttons functioning as links

### PR DESCRIPTION
**Pull request by carina-akaia**
Allows rendering buttons using \<a /\> as the root element.

```
{widget("components.atom.button", {
  href: href("community.configure", { handle }),
  label: "Configure community",
  type: "link",
})}
```

## Preview

Mainnet: https://near.org/carina.akaia.near/widget/gigs-board.pages.community.activity?handle=protocol&nearDevGovGigsContractAccountId=devgovgigs.near

### CODE REVIEW

**Review by ailisp — APPROVED** [review]
Looks good! Have you tested that existing `atom.button` still work and style same as before?

**Comment by carina-akaia** [comment]
Yes, I'll deploy preview right away

**Comment by carina-akaia** [comment]
## Preview

Mainnet: https://near.org/carina.akaia.near/widget/gigs-board.pages.community.activity?handle=protocol&nearDevGovGigsContractAccountId=devgovgigs.near

**Comment by ailisp** [comment]
Looks good!

**Pull request merged**
