### PR TITLE
fix: only allows usdt or near for solution funding request #198

### PR DESCRIPTION
**Pull request by elliotBraem**
Makes changes to solution post form and sponsorship form to only allow USDT and NEAR.

_Resolves #198_

### CODE REVIEW

**Comment by elliotBraem** [comment]
Acceptance Criteria: 

- [x] New solution and sponsorship posts can only use USDT or NEAR in the currency dropdown menu
Create new solution post [here](https://near.org/devhub.efiz.near/widget/gigs-board.pages.Create?nearDevGovGigsContractAccountId=devgovgigs.near&nearDevGovGigsWidgetsAccountId=devhub.efiz.near).
Create new sponsorship reply [here](https://near.org/devhub.efiz.near/widget/gigs-board.pages.Post?id=1000&nearDevGovGigsContractAccountId=devgovgigs.near&nearDevGovGigsWidgetsAccountId=devhub.efiz.near).
- [x] Old posts can still retroactively display the currency that was entered when they were created
Confirm works with old currencies [here](https://near.org/devhub.efiz.near/widget/gigs-board.pages.Post?id=874&nearDevGovGigsContractAccountId=devgovgigs.near&nearDevGovGigsWidgetsAccountId=devhub.efiz.near).
- [x] There is no error messages when creating solution or sponsorship using either USDT or NEAR.
See example successful sponsorship reply [here](https://near.org/devhub.efiz.near/widget/gigs-board.pages.Post?id=40&nearDevGovGigsContractAccountId=devgovgigs.petersalomonsen.near&nearDevGovGigsWidgetsAccountId=devhub.efiz.near).

There was no contract change. I had proposed changes [here](https://github.com/near/neardevhub-contract/pull/47) but learned the contract currently supports USDT.

**Review by ailisp — APPROVED** [review]
Code looks very neat and demonstration on each acceptance criteria is excellent. Thank you!

**Comment by ailisp** [comment]
@elliotBraem Could you please 
1. create a new branch for "introduce better markdown functionality",  
2. revert this PR's branch back to [b601c2b](https://github.com/near/neardevhub-widgets/pull/222/commits/b601c2b6c4393f4372eefeba074bf67eab7dc882) and force push

So I can merge this PR. Thanks!

**Comment by elliotBraem** [comment]
Sorry it took a while @ailisp , was traveling. Have just cleaned up the branch per your instructions.

**Pull request merged**
