### PR TITLE
fix: Search by author or tag won't trigger

### LINKED ISSUE #168: Search by label or author no longer works
**Describe the bug**
Current release, search by label or author on the homepage doesn't work

**To Reproduce**
1. Go to homepage
2. Search by label or author
3. Nothing happens. From console there is a form validation error: 
```
Uncaught (in promise) 
Object { value: {…}, error: ValidationError }
​
error: ValidationError: "autoSelect.label" is required
```

**Expected behavior**
It should filter out posts with given label and/or author

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura
 - Browser Firefox
 - Version 113.0.2
 
**Additional context**
It happens after current release. It was working last Thursday. Possibly related to the new form validation helper library

### PR DESCRIPTION
**Pull request by near-akaia-root**
Closes #168

## Preview

Mainnet: https://near.org/root.akaia.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near

### CODE REVIEW

**Comment by ailisp** [comment]
@near-akaia-root Do you have a preview for this fix? Also, previously our search support combination search conditions, e.g. find posts with label `abc` and by author `xyz.near` (and also combines search with keyword and sort). If I read right, your refactor dropped this feature

**Comment by ailisp** [comment]
For example:
image

I still have previous widgets deployed at my account, you can try combine the conditions here: https://near.social/#/bo.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near

**Comment by near-akaia-root** [comment]
UPD:

## Preview

https://near.org/root.akaia.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near

**Comment by near-akaia-root** [comment]
@ailisp this is how it looks on preview:

imagen

**Comment by near-akaia-root** [comment]
> @near-akaia-root If I read right, your refactor dropped this feature

It shouldn't

**Comment by ailisp** [comment]
Cool! Just tried out your preview, looks good!

**Pull request merged**
