### PR TITLE
Update admins input UI

### LINKED ISSUE #241: [Communities] Enhance community admin management and team visibility
## Problem
Currently, on the community create/edit page, the experience of setting admins for a community lacks clarity and usability. Users are queried to add admins using comma separators without indication of successful username recognition. The default assignment of admin privileges is unclear. And, there is a noticeable lag in the process. Additionally, the teams tab presents two lists, "Admins" and "Community Moderators" but the distinction between these roles is unclear, leading to potential confusion.

## User Story
As a user managing a community on DevHub, I want a clear method for setting the admins for my community, along with a clear display of those admins on the Teams page.

## Acceptance Criteria

On the community create/edit page: 
- [ ] Change the "Access control" section header to "Community Admins"
- [ ] Improve the UI experience for entering additional admins (see Admin UI Experience options below)

On the Teams tab
- [ ] Change "Admins" title to "Community Admins"

On the community homepage sidebar section:
- [ ] Change "Admins" title to "Community Admins"

## Admin UI Experience

**Option 1**
Require the selection of the primary admin #1 and then offer the ability to add more admins. Display the chosen user's profile picture to confirm successful selection.

Screenshot 2023-08-11 at 11 56 33 AM

**Option 2:** 
Make the admin #1 required and then add the option to add/delete additional admins within the same field. 

Screenshot 2023-08-11 at 12 03 22 PM

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
Resolves #241 
Preview [link](https://near.social/megha19.near/widget/app?page=community.configuration&handle=devhub-test)

### CODE REVIEW

**Comment by Megha-Dev-19** [comment]
Hey @ori-near, please take a look at the UI and let me know if it works as expected

**Comment by ori-near** [comment]
Hi @Megha-Dev-19 – this looks awesome! A few follow up requests:

1. We must require at least one admin. So a user cannot remove all admins. Just everyone except for the first one.
2. It would be great if we can leverage the suggested mention module you fixed in the previous ticket. For example, if I type @el, I would see a list of possible suggestions and clicking on them will auto complete the person. Also, ideally it wouldn't show any users who've already been added.
3. I think the "Add Admin" part could use some UX improvement, as it's not entirely clear that you need to type and then click enter. But we can revisit this later.

**Comment by Megha-Dev-19** [comment]
Hey @ori-near 
I am not sure about the first point.
Thinking as a user, I wouldn’t always enter the correct first admin, or maybe I don’t want them anymore and if I am restricted from removing them, it’s an issue.
I can disable the submit button if no admins are added. Or show an error too, to add one.
What’s your views about it.

**Comment by ori-near** [comment]
Hi @Megha-Dev-19 – we want to avoid a situation where a group is left without any admins. Essentially whoever creates the group to begin with is the default admin. They can't remove themselves unless they add a secondary admin. Let's say you are the admin of a page you created. You won't be able to remove yourself, but if you add me, I can remove you or you can remove yourself. But the last person cannot be removed unless they add someone else.

**Comment by ailisp** [comment]
We have a prevention on contract side, so if you're removing the last admin, contract would detect it and prevent you from doing so. Of course, It would be nice to have that validation on frontend

**Comment by Megha-Dev-19** [comment]
@ori-near I have added your 2nd point.
for 1st point when only one admin is there I have disabled delete (not restricted to first item), let me know if you want to change it.
I have made some updates for 3rd point as well, let me know if it is clear now
Preview [link](https://near.org/megha19.near/widget/app?page=community.configuration&handle=devhub-test)

**Comment by ori-near** [comment]
Hi @Megha-Dev-19 – this looks great, nicely done. I just have one last additional request:

5. When you click on an admin (after they've already been added, can we open their profile in a new tab instead of in the existing window? This will ensure that we don't lose progress). 

With 5 done, I consider this ticket accepted 🚀 and ready to merge.

**Comment by Megha-Dev-19** [comment]
@ori-near updated. [Link](https://near.org/megha19.near/widget/app?page=community.configuration&handle=devhub-test)

**Review by ailisp — APPROVED** [review]
Looks great to me as well. Thank you @Megha-Dev-19 !

**Pull request merged**
