### PR TITLE
Fix to showing Read More on post page #113

### PR DESCRIPTION
**Pull request by projectnoa**
Fix to showing the description section of a post collapsed when viewing the post page.

### CODE REVIEW

**Review by ailisp — APPROVED** [review]
Looks great! Thanks @projectnoa

**Comment by ailisp** [comment]
@projectnoa After deploy this PR The behavior looks reverse as the requirement:

https://near.social/#/mob.near/widget/MyPage?accountId=devgovgigs.near (should clamp, but it does not)

https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Post?id=532 (should not clamp, but it clamps)

Can you look into it?

**Comment by ailisp** [comment]
I fixed it in https://github.com/near/neardevhub-widgets/pull/127

**Comment by projectnoa** [comment]
Thanks @ailisp!

**Pull request merged**
